language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
install:
  - "npm install"
# env:
#   global:
#     - PGUSER=chi
#     - PGDATABASE=wayfarer
#     - PGPASSWORD=Brain.box8
#     - PGPORT=5432
before_script:
  - psql -c "CREATE DATABASE wayfarer;" -U postgres
  - psql -c "CREATE USER chi WITH PASSWORD 'Brain.box8';" -U postgres
  - psql -c "CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL, 
    password VARCHAR NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
  );" -U chi
  # - psql -d wayfarer -f db.sql -U postgres
script:
  - npm run test
after_script:
  - psql -c "DROP DATABASE wayfarer;" -U postgres
after_success:
  - npm run coverage
