language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - "npm install"
env:
  global:
    - PGHOST=35.188.116.232
    - PGUSER=chii
    - PGDATABASE=wayfarer
    - PGPASSWORD=Brain.box8
    - PGPORT=5432
    - NODE_ENV=test
    - PORT=5000
    - JWT_SECRET=wayfarersecretkey
    - CODECLIMATE_REPO_TOKEN=b06c619dc94c3b4e1f5c8a6dc056cdb10eb088a3ee7061cc701f7c106bd85848
script:
  - npm run test
after_success:
  - npm run coverage
