language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
postgres:
  database: wayfarer
  adapter: postgresql
  username: postgres
install:
  - "npm install"
before_script:
  - psql -c "CREATE DATABASE wayfarer;" -U postgres
  - psql -d wayfarer -f db.sql -U postgres
  - psql -c "SELECT * FROM users;" -U postgres
script:
  - npm run test
after_script:
  - psql -c "DROP DATABASE wayfarer;" -U postgres
after_success:
  - npm run coverage
