language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
env:
  global:
  - NODE_ENV=test
before_script:
  - psql -c 'create database wayfarer_test;' -U postgres
  - psql -c "CREATE USER chi WITH PASSWORD null;" -U postgres
  - psql -U postgres -d wayfarer_test -a -f ./db.sql
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coverage
  - psql -c "DROP DATABASE wayfarer_test;" -U postgres
