language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
install:
  - "npm install"
postgres:
  database: wayfarer
  username: postgres
before_script:
  - psql -c "CREATE DATABASE wayfarer_test;" -U postgres
  - psql -c "CREATE USER chi WITH PASSWORD null;" -U postgres
  - psql -f db.sql -d wayfarer_test -U postgres
  - psql -c "SELECT * FROM buses;" -U postgres
script:
  - npm run test
after_script:
  - psql -c "DROP DATABASE wayfarer_test;" -U postgres
after_success:
  - npm run coverage
