language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
    - NODE_ENV: test
    - PGHOST: localhost
    - PGUSER: chi
    - PGDATABASE: myapp_test
    - PGPASSWORD: null
    - PGPORT: 5432
    - PORT: 5000
services:
  - postgresql
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - psql -c "CREATE DATABASE myapp_test;" -U postgres
  - psql -c "CREATE USER chi WITH PASSWORD null;" -U postgres
  - psql -U postgres -d wayfarer_test -a -f ./db.sql
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coverage
  - psql -c "DROP DATABASE wayfarer_test;" -U postgres
