language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE wayfarer;" -U postgres
  - psql -d wayfarer -f db.sql -U postgres"
postgres:
  database: wayfarer
install:
  - "npm install"
script:
  - npm run test
after_success:
  - npm run coverage
