language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - "psql -f db.sql -U postgres"
install:
  - "npm install"
script:
  - npm run test
after_success:
  - npm run coverage
