language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  global:
    - NODE_ENV: test
    - PGHOST: localhost
    - PGUSER: chi
    - PGDATABASE: wayfarer_test
    - PGPASSWORD: null
    - PGPORT: 5432
services:
  - postgresql
postgres:
  - postgresql: &postgresql
  - adapter: postgresql
  - database: wayfarer_test
  - username: chi
before_script:
  - psql -c "CREATE DATABASE wayfarer_test;" -U postgres
  - psql -c "CREATE USER chi WITH PASSWORD null;" -U postgres
  - psql -U postgres -d wayfarer_test -a -f ./db.sql
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coverage
  - psql -c "DROP DATABASE wayfarer_test;" -U postgres
