language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
install:
  - "npm install"
before_script:
  - psql -c "CREATE DATABASE wayfarer;" -U postgres
  - psql -c "CREATE USER chi WITH PASSWORD null;" -U postgres
  - psql -f db.sql -U postgres
  - psql -c "SELECT * FROM buses;" -U postgres
script:
  - npm run test
after_script:
  - psql -c "DROP DATABASE wayfarer;" -U postgres
after_success:
  - npm run coverage
